// <auto-generated />
using System;
using ConsultNote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultNote.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707072018_AddCustomerConsultationConditionFields")]
    partial class AddCustomerConsultationConditionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ConsultNote.Data.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.ConsultationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ConsultationLogs");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyDbReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormFuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormVehicleBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormVehicleDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormVehicleName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasBusinessExperienceOverOneYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasDriverLicenseOverOneYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceAge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConsultedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastContactAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mileage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Consulting");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Estimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelTypes")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "경차",
                            Name = "캐스퍼",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 전기",
                            IsActive = true,
                            Memo = "경차",
                            Name = "레이",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "경차",
                            Name = "모닝",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "소형",
                            Name = "캐스퍼",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, LPG",
                            IsActive = true,
                            Memo = "준중형",
                            Name = "아반떼",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "준중형",
                            Name = "아반떼N",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "준중형",
                            Name = "EV4",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "중형",
                            Name = "쏘나타",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "중형",
                            Name = "아이오닉6",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "중형",
                            Name = "아이오닉6N",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "중형",
                            Name = "K5",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "중형",
                            Name = "G70",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "준대형",
                            Name = "그랜저",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "준대형",
                            Name = "K8",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "준대형",
                            Name = "G80",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "준대형",
                            Name = "G80 electric",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "대형",
                            Name = "K9",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "대형",
                            Name = "G90",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "코나",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "코나EV",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "베뉴",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "셀토스",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "하이브리드",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "니로",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "EV3",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Brand = "쉐보레",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "트렉스 크로스오버",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Brand = "쉐보레",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "트레일블레이저",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Brand = "KGM",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "티볼리",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Brand = "르노코리아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "소형SUV",
                            Name = "아르카나",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "하이브리드, 가솔린",
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "투싼",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "스포티지",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "EV5",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "EV6",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "GV60",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            Brand = "쉐보레",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "이쿼녹스",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            Brand = "KGM",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "액티언",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            Brand = "KGM",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "준중형SUV / 5인",
                            Name = "토레스",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "하이브리드, 가솔린",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "싼타페",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "아이오닉5",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "아이오닉5N",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "하이브리드, 가솔린, 디젤",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "쏘렌토",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "GV70",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "GV70 electric",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            Brand = "KGM",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "렉스턴",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            Brand = "르노코리아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "중형SUV / 5, 6, 7인승",
                            Name = "그랑 콜레오스",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드",
                            IsActive = true,
                            Memo = "대형SUV / 내연: 7, 9인승 / 전기: 6, 7인승",
                            Name = "팰리세이드",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "대형SUV / 내연: 7, 9인승 / 전기: 6, 7인승",
                            Name = "아이오닉9",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "대형SUV / 내연: 7, 9인승 / 전기: 6, 7인승",
                            Name = "EV9",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            Brand = "제네시스",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린",
                            IsActive = true,
                            Memo = "대형SUV / 5, 6, 7인승",
                            Name = "GV80",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            Brand = "르노코리아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Memo = "대형SUV / 내연: 7, 9인승 / 전기: 6, 7인승",
                            Name = "필랑트",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드, LPG",
                            IsActive = true,
                            Memo = "RV/MPV(승합차) / 좌석 옵션 다양함",
                            Name = "스타리아",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            Brand = "현대",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "RV/MPV(승합차)",
                            Name = "스타리아 일렉트릭",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "가솔린, 하이브리드",
                            IsActive = true,
                            Memo = "RV/MPV(승합차) / 7, 9인승",
                            Name = "카니발",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            Brand = "기아",
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelTypes = "전기",
                            IsActive = true,
                            Memo = "RV/MPV(승합차) / 5인승",
                            Name = "PV5",
                            UpdatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Attachment", b =>
                {
                    b.HasOne("ConsultNote.Data.Entities.Customer", "Customer")
                        .WithMany("Attachments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.ConsultationLog", b =>
                {
                    b.HasOne("ConsultNote.Data.Entities.Customer", "Customer")
                        .WithMany("ConsultationLogs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Estimate", b =>
                {
                    b.HasOne("ConsultNote.Data.Entities.Customer", "Customer")
                        .WithMany("Estimates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConsultNote.Data.Entities.Customer", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ConsultationLogs");

                    b.Navigation("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
